volumes:
  mosquitto_data:
  mosquitto_log:
services:
  factory-simulator:
    build:
      context: ./factory_ui_simulator/
      dockerfile: Dockerfile
      args:
        WEBAPP_PORT: 5001  # Default port for the web app
    ports:
      - 5001:5001
    environment:
        MQTT_BROKER: tshirt-factory-001-mqtt # it seems jquery cannot resolve mqtt address, replace with host ip or url address
        MQTT_PORT: 1883
        MQTT_WS_PORT: 9001
        WEBAPP_PORT: 5001 # The flask app port number, if this changes, change also the port tuple above
        FACTORY_SITE_ID: tshirt-factory-001
        MACHINE_DATA_PUBLISH_INTERVAL: 10 # in seconds
        PRODUCTION_LOOP_INTERVAL: 5 # in seconds
        MACHINE_DATA_REST_REQUEST_INTERVAL: 10 # in seconds
    networks:
      - aws-factory-network
      - tshirt-factory-001-network

  frontend:
    build:
      context: ./customer-order-ui/
      dockerfile: Dockerfile
      args:
        API_URL: factory-simulator:5001  # Default API URL for the frontend
    ports:
      - "8080:80" 
    environment:
        # Pass the env variable directly into the container
       - API_URL=factory-simulator:5001
    restart: always
    networks:
      - aws-factory-network
networks:
  aws-factory-network:
    driver: bridge
  tshirt-factory-001-network:
    external:
      name: tshirt-factory-001_tshirt-factory-001-network